/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface DB {}




// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.